<?php

$data = array(
	array("index"=>1,"rent"=>1109,"type"=>"Single-Family Home","beds"=>"2 beds","bath"=>"3 baths","size"=>"1804 sqft","address"=>"4003 Manor Dr,Stroudsburg,PA 18360","img"=>"img/h1.jpg","description"=>"Exceptional 5.5 Acre McMichael's Creekfront Home In Hamilton Township! This Delightful Ranch Offers 2-3 Bedrooms with 1 Full Bath, 2 Half Baths & Nearly 2,000 Square Foot Of Finished Living Space Providing Limitless Possibilities. An Open Concept Layout With Cathedral Ceilings & Custom Woodwork Showcase Beautiful Log Accents & Hardwood Floors! "),
	array("index"=>2,"rent"=>845,"type"=>"Single-Family Home","beds"=>"3 beds","bath"=>"2 baths","size"=>"1296 sqft","address"=>"2176 N 5th st,Stroudsburg,PA 18360","img"=>"img/h2.jpg","description"=>"Ranch in the heart of the Pocono Mountains, situated in Downtown Stroudsburg. With recently updated kitchen, baths, roof and new flooring throughout. This home offers a covered front porch and great backyard with a covered patio for you to sit back and relax with family and friends."),
	array("index"=>3,"rent"=>863,"type"=>"Single-Family Home","beds"=>"4 beds","bath"=>"2 baths","size"=>"1872 sqft","address"=>"1427 Route 715,Stroudsburg,PA 18360","img"=>"img/h3.jpg","description"=>"This property is being offered at Public Auction on 02-28-2019. Visit Auction.com now to view additional photos, Property Inspection Report with title information, plat maps and interior inspection reports when available. Auction.com is the nation's leading real estate transaction platform focused exclusively on the sale of residential foreclosure and bank-owned properties."),
	array("index"=>4,"rent"=>1286,"type"=>"Apartment","beds"=>"5 beds","bath"=>"3 baths","size"=>"3420 sqft","address"=>"1925 Kyle Dr,Stroudsburg,PA 18360","img"=>"img/h4.jpg","description"=>"Two story colonial style home in East View Estates. Tremendous kitchen with all appliances. Four large bedrooms on the second floor with another in the basement level. Oil heat with 3 zones and central air."),
	array("index"=>5,"rent"=>1108,"type"=>"Apartment","beds"=>"5 beds","bath"=>"3 baths","size"=>"3852 sqft","address"=>"5595 Olde Mill Run,Stroudsburg,PA 18360","img"=>"img/h5.jpg","description"=>"Executive style home,set on secluded wooded lot in lovely neighborhood,circular driveway,solid brick exterior,front covered porch,terrace in back,20 x 40 ft in ground pool.Holiday cooking sized eat in kitchen w/island & SS appliances,formal dining room,living room w/FP & triple bay window, greeting room, study w/FP, Master bedroom suite."),
	array("index"=>6,"rent"=>1063,"type"=>"Apartment","beds"=>"5 beds","bath"=>"4 baths","size"=>"4085 sqft","address"=>"121 Buckfield Ln,Stroudsburg,PA 18360","img"=>"img/h6.jpg","description"=>"This home offers an impressive expansive foyer with spiral oak staircase. The main floor has a formal living room, formal dining room, den, library, and chef''s eat in kitchen. The home offers 4 large and well appointed bedrooms for a spacious yet smart use of space and 4 full baths."),
	array("index"=>7,"rent"=>1593,"type"=>"Single-Family Home","beds"=>"4 beds","bath"=>"3 baths","size"=>"2678 sqft","address"=>"1103 Gap View Holw,Stroudsburg,PA 18360","img"=>"img/h7.jpg","description"=>"Offers all the check marks you are looking for.....Hardwood flooring, fireplace, sunroom, 4 bedrooms, in-law suite, new appliances, freshly paint,2 car garage ,PLUS PLUS PLUS."),
	array("index"=>8,"rent"=>1427,"type"=>"Single-Family Home","beds"=>"4 beds","bath"=>"3 baths","size"=>"1918 sqft","address"=>"141 Price Dr,Stroudsburg,PA 18360","img"=>"img/h8.jpg","description"=>"FABULOUS EXTENDED BRICK AND VINYL RANCH WITH FULL IN- LAW APARTMENT WALK IN LOWER LEVEL. NEW UPGRADED KITCHEN FEATURING GRANITE COUNTERTOPS AND STAINLESS APPLIANCES. CERAMIC TILE AND HARDWOOD FLOORS. MASSIVE FAMILY ROOM & FORMAL DININGROOM WITH FIREPLACE."),
	array("index"=>9,"rent"=>1778,"type"=>"Single-Family Home","beds"=>"5 beds","bath"=>"3 baths","size"=>"5029 sqft","address"=>"1226 Greenwood Rd,Stroudsburg,PA 18360","img"=>"img/h9.jpg","description"=>"The open floor plan encompasses 5 spacious bedrooms with plenty of room for study, sleep and storage, 3 and a half bathrooms, and a stylish gourmet kitchen that flows through to the dining room with fireplace. The expansive living room opens up to a spacious rear four season sun room."),
	array("index"=>10,"rent"=>809,"type"=>"Single-Family Home","beds"=>"4 beds","bath"=>"1 baths","size"=>"2046 sqft","address"=>"854 Thomas St,Stroudsburg,PA 18360","img"=>"img/h10.jpg","description"=>"This property was recently foreclosed by a bank or financial institution and is now available to purchase online at Auction.com ending 02-21-2019. Visit Auction.com now to view additional photos, Property Inspection Report with title information, plat maps and interior inspection reports when available.")
)

?>